CREATE TABLE CLIENTES (
    CPF CHAR(11) PRIMARY KEY, 
    NOME VARCHAR(100) NOT NULL, 
    IDADE INT NOT NULL
);

CREATE TABLE TELEFONES (
    CPF_CLIENTE CHAR(11) PRIMARY KEY,
    DDD CHAR(2) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    CONSTRAINT FK_TELEFONES_CLIENTES FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES(CPF)
);
